feat: scroll connector
defi-wonderland/connext-monorepo pull request #44
Opened 2023-11-20 14:41 UTC by 0xDiscotech

Created `ScrollHubConnector` and `ScrollSpokeConnector` contracts.
They are completely unit tested, and also both of them have 2 integration tests: 1 for sending a message, and another one to receive it.

2023-11-27 15:37 UTC, ashitakah requested changes
Really well done !! 🔥

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/receiveMessage/ScrollHubConnector.t.sol
> +    l1ScrollMessenger.relayMessage(
also here you can fuzz the two 0 like :
```
test_processMessage(uint256 _lastIndex, uint256 _value, uint256 _messageNonce);
l1ScrollMessenger.relayMessage(
   mirrorConnector,
      address(scrollHubConnector),
      _value,
      _messageNonce,
      abi.encodeWithSelector(Connector.processMessage.selector, _data)
    );
```

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/Common.sol
> +contract Common is ConnectorHelper {
Maybe create a common file with everything in common with the 2 tests?

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/ScrollHubConnector.t.sol
> +    uint256 _nonce = 67193;
fuzz

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/ScrollHubConnector.t.sol
> +    uint256 _gasExtra = 1000;
fuzz and assume like vm.assume(_gasExtral > 10 &&  _gasExtral< 2000)

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/ScrollHubConnector.t.sol
> +    uint256 _refundAddrBalanceBef = address(_refundAddress).balance;
_addrBalanceBef

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/BaseScroll.t.sol
> +    uint256 _validMessageLength = 32;
declare as constant at the beginning

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/BaseScroll.t.sol
> +  function test_checkMessageLength() public {
function test_checkMessageLength(bytes memory _data) public {
   vm.assume(data.length == VALID_MESSAGE_LENGTH)
    assertEq(baseScroll.forTest_checkMessageLength(_data), true);
  }

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollHubConnector.t.sol
> +    address _refundAddress = makeAddr("refundAddress");
move to the top with the order EOAs

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollSpokeConnector.t.sol
> +contract Unit_Connector_ScrollSpokeConnector_VerifySender is Base {
trick:

```
contract Unit_Connector_ScrollSpokeConnector_VerifySender is Base {
 modifier happyPath(address _mirrorConnector) {
   vm.mockCall(
      _amb,
      abi.encodeWithSelector(IL2ScrollMessenger.xDomainMessageSender.selector),
      abi.encode(_mirrorConnector)
    );
   vm.startPrank(_mirrorConnector);
}
  function test_returnFalseIfOriginSenderNotMirror(address _originSender, address _mirrorConnector) public happyPath(_mirrorConnector) {
    vm.assume(_originSender != _mirrorConnector);

    assertEq(scrollSpokeConnector.forTest_verifySender(_originSender), false);
  }

  function test_returnTrueIfOriginSenderIsMirror(address _mirrorConnector) public  happyPath(_mirrorConnector){
    assertEq(scrollSpokeConnector.forTest_verifySender(_mirrorConnector), true);
  }
}
```

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollSpokeConnector.t.sol
> +  function test_callAMBSendMessage() public {
I would like to have another test expecting the event

2023-11-27 15:37 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollSpokeConnector.t.sol
> +  bytes32 public rootSnapshot = keccak256(abi.encodePacked("rootSnapshot"));
is needed to encode the "rootSnapshot" or can be anything

2023-11-27 17:13 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/receiveMessage/L1ScrollMessengerForTest.sol
> +  address internal constant DEFAULT_XDOMAIN_MESSAGE_SENDER = address(1);
That is the address that they're using on their contract haha

2023-11-27 17:15 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/receiveMessage/L1ScrollMessengerForTest.sol
> +  IL1ScrollMessenger public immutable L1_SCROLL_MESSENGER;
To remove the part of the function that validates the proof. This is the context:
<img width="907" alt="image" src="https://github.com/defi-wonderland/connext-monorepo/assets/131301107/1af25ddd-41f9-4164-b155-c56ace994d8c">

2023-11-27 17:17 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/Common.sol
> +contract Common is ConnectorHelper {
The problem is that in one I use the 'real' deployed `L1ScrollMessenger` AMB, and in the other I deploy the `L1ScrollMessengerForTest`, and I need to make modifications based on that difference

2023-11-27 17:24 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollSpokeConnector.t.sol
> +  bytes32 public rootSnapshot = keccak256(abi.encodePacked("rootSnapshot"));
can be anything actually, will remove the encoded and hash

2023-11-27 17:25 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts/messaging/connectors/scroll/ScrollHubConnector.sol
> +    if (_encodedData.length > 0) _refundAddress = abi.decode(_encodedData, (address));
Good catch, I like more this way 👍

2023-11-27 17:30 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts/messaging/connectors/scroll/ScrollHubConnector.sol
> +    L1_SCROLL_MESSENGER.sendMessage{value: msg.value}(
The payable function is declared on `HubConnector` contract: 
`function sendMessage(bytes memory _data, bytes memory _encodedData) external payable;` 

As ` _sendMessage()` is internal, it can't be payable - but is not needed since the one that executes it is the previous mentioned `sendMessage()` function

2023-11-27 17:39 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/receiveMessage/ScrollHubConnector.t.sol
> +    l1ScrollMessenger.relayMessage(
True

2023-11-27 17:42 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/ScrollHubConnector.t.sol
> +    uint256 _gasExtra = 1000;
Why the assumption of `_gasExtral< 2000` is needed?

2023-11-27 18:15 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/ScrollHubConnector.t.sol
> +    uint256 _gasExtra = 1000;
I updated it for `type(uint248).max - _fee`

2023-11-27 18:24 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollSpokeConnector.t.sol
> +contract Unit_Connector_ScrollSpokeConnector_VerifySender is Base {
Nice!

2023-11-27 18:24 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollSpokeConnector.t.sol
> +contract Unit_Connector_ScrollSpokeConnector_VerifySender is Base {
is cleaner

2023-11-27 18:33 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/ScrollSpokeConnector.t.sol
> +  function test_callAMBSendMessage() public {
The `_sendMessage` function doesn't emit any events. The `SpokeConnector`'s `send()` function does, but I think that test is out of the scope of this unit tests right?

2023-11-27 19:03 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/receiveMessage/ScrollHubConnector.t.sol
> +  function test_processMessage() public {
`lastIndex` must be one because the contract doesn't store any root. I can't fuzz it since the event won't never match

2023-11-27 19:04 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/receiveMessage/ScrollHubConnector.t.sol
> +    l1ScrollMessenger.relayMessage(
Update: Can't fuzz `_value` - it must be 0 since the value sent on the connector is always 0.

2023-11-28 22:19 UTC, ashitakah commented on packages/deployments/contracts/contracts/messaging/connectors/scroll/ScrollHubConnector.sol
> +    L1_SCROLL_MESSENGER.sendMessage{value: msg.value}(
thanks for clarifying!

2023-11-28 22:23 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/integration/l1/sendMessage/ScrollHubConnector.t.sol
> +    uint256 _gasExtra = 1000;
too much better

2023-11-28 22:26 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/scroll/unit/BaseScroll.t.sol
> +  function test_checkMessageLength() public {
🔥

2023-12-04 13:35 UTC, ashitakah commented
looks good

2023-12-04 13:36 UTC, merged