feat: taiko connector
defi-wonderland/connext-monorepo pull request #46
Opened 2023-12-04 20:25 UTC by 0xDiscotech

Created `TaikoSpokeConnector` and `TaikoHubConnector` contracts with their unit tests and also integration test for the send and receive flows on each one.
Added natspec for each contract and interface
Added the deployment info the `deployConfig/shared.ts` file

2023-12-07 12:04 UTC, ashitakah requested changes
looks good overall, just a few comments about improve the style of the tests. Nice Work 🔥

2023-12-07 12:04 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/taiko/unit/TaikoSpokeConnector.t.sol
> +    vm.assume(_data.length != 32);
constant

2023-12-07 14:39 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts/messaging/connectors/taiko/TaikoHubConnector.sol
> +  function _sendMessage(bytes memory _data, bytes memory) internal override {
That's the interface from the function I'm inheriting and overriding. I didn't add a name to the second param because it's unused

2023-12-07 14:44 UTC, 0xDiscotech commented on packages/deployments/contracts/contracts_forge/messaging/connectors/taiko/integration/l1/sendMessage/TaikoHubConnector.t.sol
> +    bytes memory _encodedData = "";
I will try, but it should always work since the encoded data argument is never used, so it doesn't matter what is sent

2023-12-08 12:25 UTC, ashitakah commented on packages/deployments/contracts/contracts/messaging/connectors/taiko/TaikoHubConnector.sol
> +  function _sendMessage(bytes memory _data, bytes memory) internal override {
👍

2023-12-08 12:34 UTC, ashitakah commented on packages/deployments/contracts/contracts_forge/messaging/connectors/taiko/unit/TaikoHubConnector.t.sol
> +    bytes memory _encodedData = "";
yes sorry my mistake

2023-12-08 12:35 UTC, ashitakah approved these changes

2023-12-08 12:48 UTC, merged